import codecs
with codecs.open("admin/build/index.html", "r", "utf-8") as f:
    text = f.read()
translations = {
    "All systems operational": "所有系统运行正常",
    "RAG Configuration": "RAG 配置",
    "Successfully processed batch synchronization task. 项目 updated: 452.": "成功处理批量同步任务。已更新项目：452。",
    "Error Rate": "错误率",
    "Medium": "中等",
    "Similarity Threshold": "相似度阈值",
    "Knowledge Management": "知识管理",
    "Cancel": "取消",
    "Below critical threshold (2%)": "低于临界阈值(2%)",
    "EdTech Digest": "教育科技文摘",
    "Max Generation Tokens": "最大生成Token",
    "Higher Ed": "高等教育",
    "Last 24 Hours": "过去24小时",
    "The End of the Sync Meeting": "同步会议的终结",
    "Executive Summary": "执行摘要",
    "System Status": "系统状态",
    "Manage and monitor RSS and custom data feeds providing content for Learning Scout analysis.": "管理和监控为 Learning Scout 分析提供内容的 RSS 和自定义数据订阅源。",
    "Failed to authenticate user token from remote identity provider.": "从远程身份提供商验证用户令牌失败。",
    "System Information": "系统信息",
    "Last Scrape": "上次抓取",
    "Last 7 Days": "过去7天",
    "Save Changes": "保存更改",
    "General Settings": "通用设置",
    "User Profile": "用户资料",
    "Email": "电子邮件",
    "Password": "密码",
    "Update": "更新",
    "Items": "项目",
    "Copy Summary": "复制摘要",
    "Search": "搜索",
    "Dashboard": "控制台",
    "Logs": "日志",
    "Settings": "设置",
    "Feeds": "订阅源",
    "Active": "活跃",
    "Inactive": "不活跃",
    "Pending": "待处理",
    "Error": "错误",
    "Warning": "警告",
    "Info": "信息",
    "Refresh": "刷新",
    "Download": "下载",
    "Upload": "上传",
    "Delete": "删除",
    "Add": "添加",
    "Create": "创建",
    "Cancel": "取消",
    "Confirm": "确认",
    "Submit": "提交",
    "Yes": "是",
    "No": "否",
    "Next": "下一步",
    "Previous": "上一步",
    "Done": "完成",
    "Close": "关闭",
    "Open": "打开",
    "Settings": "设置",
    "Profile": "资料",
    "Logout": "退出",
    "Login": "登录",
    "Register": "注册",
    "Forgot Password": "忘记密码",
    "Reset Password": "重置密码",
    "Help": "帮助",
    "About": "关于",
    "Contact": "联系",
    "Terms of Service": "服务条款",
    "Privacy Policy": "隐私政策",
    "Admin Console": "管理控制台",
    "New Report": "新建报告",
    "Search resources...": "搜索资源...",
    "Support": "帮助",
    "Overview": "概览",
    "Monitor your system's extraction performance and health metrics.": "监控系统的抽取性能与健康指标",
    "Run Now": "立即执行",
    "Total Items": "总项目数",
    "from last week": "较上周",
    "New Today": "今日新增",
    "Active Feeds": "活跃订阅源",
    "Success Rate": "成功率",
    "Recent Activity": "近期活动",
    "View All": "查看全部",
    "Filter": "筛选",
    "Item": "项目",
    "Source": "来源",
    "Status": "状态",
    "Time": "时间",
    "Action": "操作",
    "Extracted article on AI trends": "抽取了关于AI趋势的文章",
    "Added new RSS feed": "添加了新的RSS源",
    "Failed to fetch from source": "从源获取失败",
    "Updated system settings": "更新了系统设置",
    "Database backup completed": "数据库备份已完成",
    "Extracted": "成功",
    "System": "系统",
    "Failed": "失败",
    "Just now": "刚刚",
    "2h ago": "2小时前",
    "5h ago": "5小时前",
    "1d ago": "1天前",
    "View": "查看",
    "Retry": "重试",
    "Edit": "编辑"
}
for k, v in translations.items():
    text = text.replace(f">{k}<", f">{v}<")
    text = text.replace(f">{k} ", f">{v} ")
    text = text.replace(f" {k}<", f" {v}<")
    text = text.replace(f"'{k}'", f"'{v}'")
    text = text.replace(f'"{k}"', f'"{v}"')
    # Only globally replace if it's safe (multi-word, specific strings)
    if len(k) > 10:
        text = text.replace(k, v)
with codecs.open("admin/build/index.html", "w", "utf-8") as f:
    f.write(text)
print("Translation applied successfully to index.html")
